export interface Pergunta {
    id: number;
    pergunta: string;
    alternativas: string[];
    respostaCorreta: number;
    dificuldade: 'facil' | 'medio' | 'dificil';
}

export interface CategoriaQuiz {
    id: string;
    nome: string;
    descricao: string;
    icone: string;
    cor: string;
    perguntas: Pergunta[];
}

export const categorias: CategoriaQuiz[] = [
    {
        id: 'javascript',
        nome: 'JavaScript',
        descricao: 'Domine a linguagem da web moderna',
        icone: 'javascript',
        cor: '#F7DF1E',
        perguntas: [
            {
                id: 1,
                pergunta: 'Qual método é usado para adicionar um elemento ao final de um array?',
                alternativas: ['push()', 'pop()', 'shift()', 'unshift()'],
                respostaCorreta: 0,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'O que o operador "===" faz em JavaScript?',
                alternativas: [
                    'Compara apenas valores',
                    'Compara valor e tipo',
                    'Atribui um valor',
                    'Compara referências',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 3,
                pergunta: 'Qual é o resultado de typeof null?',
                alternativas: ['"null"', '"undefined"', '"object"', '"boolean"'],
                respostaCorreta: 2,
                dificuldade: 'medio',
            },
            {
                id: 4,
                pergunta: 'O que é uma closure em JavaScript?',
                alternativas: [
                    'Uma função que fecha o navegador',
                    'Uma função que tem acesso ao escopo externo',
                    'Um método para fechar conexões',
                    'Um tipo de loop',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 5,
                pergunta: 'Qual método converte um JSON em objeto JavaScript?',
                alternativas: ['JSON.parse()', 'JSON.stringify()', 'JSON.convert()', 'JSON.toObject()'],
                respostaCorreta: 0,
                dificuldade: 'facil',
            },
            {
                id: 6,
                pergunta: 'O que a keyword "let" faz diferente de "var"?',
                alternativas: [
                    'Nada, são iguais',
                    'let tem escopo de bloco',
                    'let é mais rápido',
                    'let só funciona em funções',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 7,
                pergunta: 'Qual é o output de: console.log(0.1 + 0.2 === 0.3)?',
                alternativas: ['true', 'false', 'undefined', 'NaN'],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 8,
                pergunta: 'O que é o Event Loop no JavaScript?',
                alternativas: [
                    'Um loop for especial',
                    'Gerencia a execução assíncrona de callbacks',
                    'Um evento de mouse',
                    'Um tipo de array',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 9,
                pergunta: 'Qual método retorna um novo array com elementos filtrados?',
                alternativas: ['map()', 'filter()', 'reduce()', 'find()'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 10,
                pergunta: 'O que são Promises em JavaScript?',
                alternativas: [
                    'Variáveis globais',
                    'Representam o resultado futuro de uma operação assíncrona',
                    'Funções síncronas',
                    'Tipos de dados primitivos',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
        ],
    },
    {
        id: 'python',
        nome: 'Python',
        descricao: 'A linguagem mais versátil do mundo',
        icone: 'python',
        cor: '#3776AB',
        perguntas: [
            {
                id: 1,
                pergunta: 'Qual é a forma correta de criar uma lista em Python?',
                alternativas: ['list = (1, 2, 3)', 'list = [1, 2, 3]', 'list = {1, 2, 3}', 'list = <1, 2, 3>'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'O que faz o método strip() em uma string?',
                alternativas: [
                    'Remove todos os espaços',
                    'Remove espaços do início e fim',
                    'Remove caracteres especiais',
                    'Inverte a string',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 3,
                pergunta: 'Qual é a diferença entre uma lista e uma tupla?',
                alternativas: [
                    'Nenhuma diferença',
                    'Tuplas são imutáveis',
                    'Listas são mais rápidas',
                    'Tuplas só aceitam números',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 4,
                pergunta: 'O que é um decorator em Python?',
                alternativas: [
                    'Um tipo de variável',
                    'Uma função que modifica outra função',
                    'Um comentário especial',
                    'Um tipo de classe',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 5,
                pergunta: 'Como se cria um dicionário vazio em Python?',
                alternativas: ['dict = []', 'dict = ()', 'dict = {}', 'dict = set()'],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
            {
                id: 6,
                pergunta: 'Qual keyword é usada para herança de classes?',
                alternativas: ['extends', 'inherits', 'class Filho(Pai)', 'class Filho extends Pai'],
                respostaCorreta: 2,
                dificuldade: 'medio',
            },
            {
                id: 7,
                pergunta: 'O que é list comprehension?',
                alternativas: [
                    'Uma forma de ler listas',
                    'Sintaxe concisa para criar listas',
                    'Um tipo de sort',
                    'Um método de lista',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 8,
                pergunta: 'Qual é o resultado de: len("Python")?',
                alternativas: ['5', '6', '7', 'Error'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 9,
                pergunta: 'O que é o GIL (Global Interpreter Lock)?',
                alternativas: [
                    'Um framework',
                    'Mecanismo que impede execução paralela real de threads',
                    'Um gerenciador de pacotes',
                    'Um tipo de variável global',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 10,
                pergunta: 'Qual é a forma correta de importar um módulo?',
                alternativas: ['#include math', 'using math', 'import math', 'require("math")'],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
        ],
    },
    {
        id: 'html',
        nome: 'HTML',
        descricao: 'A linguagem de marcação da web',
        icone: 'html',
        cor: '#E44D26',
        perguntas: [
            {
                id: 1,
                pergunta: 'O que significa HTML?',
                alternativas: [
                    'Hyper Text Markup Language',
                    'High Tech Modern Language',
                    'Home Tool Markup Language',
                    'Hyper Transfer Markup Language',
                ],
                respostaCorreta: 0,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'Qual tag é usada para o maior título?',
                alternativas: ['<heading>', '<h6>', '<h1>', '<title>'],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
            {
                id: 3,
                pergunta: 'Qual tag cria um link em HTML?',
                alternativas: ['<link>', '<a>', '<href>', '<url>'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 4,
                pergunta: 'Qual atributo define o destino de um link?',
                alternativas: ['src', 'link', 'href', 'url'],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
            {
                id: 5,
                pergunta: 'Qual é a tag semântica para o conteúdo principal?',
                alternativas: ['<div>', '<section>', '<main>', '<content>'],
                respostaCorreta: 2,
                dificuldade: 'medio',
            },
            {
                id: 6,
                pergunta: 'Qual tag é usada para criar uma lista não ordenada?',
                alternativas: ['<ol>', '<list>', '<ul>', '<nl>'],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
            {
                id: 7,
                pergunta: 'O que o atributo "alt" faz na tag <img>?',
                alternativas: [
                    'Define a largura da imagem',
                    'Define um texto alternativo para a imagem',
                    'Define o link da imagem',
                    'Define a borda da imagem',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 8,
                pergunta: 'Qual é a diferença entre <div> e <span>?',
                alternativas: [
                    'Nenhuma diferença',
                    '<div> é bloco, <span> é inline',
                    '<span> é bloco, <div> é inline',
                    'Ambos são block-level',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 9,
                pergunta: 'Qual tag HTML5 é usada para vídeos?',
                alternativas: ['<media>', '<movie>', '<video>', '<film>'],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
            {
                id: 10,
                pergunta: 'O que é o DOCTYPE em HTML?',
                alternativas: [
                    'Um elemento visual',
                    'Declara o tipo e versão do documento HTML',
                    'Um comentário obrigatório',
                    'Uma tag de metadados',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
        ],
    },
    {
        id: 'css',
        nome: 'CSS',
        descricao: 'Estilização e layout de páginas web',
        icone: 'css',
        cor: '#1572B6',
        perguntas: [
            {
                id: 1,
                pergunta: 'O que significa a sigla CSS?',
                alternativas: [
                    'Computer Style Sheets',
                    'Creative Style System',
                    'Cascading Style Sheets',
                    'Colorful Style Sheets',
                ],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'O que é Flexbox?',
                alternativas: [
                    'Um framework CSS',
                    'Um modelo de layout unidimensional',
                    'Um tipo de animação',
                    'Uma propriedade de cor',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 3,
                pergunta: 'Qual propriedade CSS controla a transparência?',
                alternativas: ['visibility', 'transparency', 'opacity', 'display'],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
            {
                id: 4,
                pergunta: 'O que é CSS Grid?',
                alternativas: [
                    'Um modelo de layout bidimensional',
                    'Uma tabela HTML',
                    'Um framework JavaScript',
                    'Um tipo de fonte',
                ],
                respostaCorreta: 0,
                dificuldade: 'medio',
            },
            {
                id: 5,
                pergunta: 'Qual a diferença entre margin e padding?',
                alternativas: [
                    'São iguais',
                    'Margin é espaço externo, padding é interno',
                    'Padding é espaço externo, margin é interno',
                    'Ambos controlam a cor',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 6,
                pergunta: 'O que é um pseudo-elemento CSS?',
                alternativas: [
                    'Um elemento HTML falso',
                    'Permite estilizar partes específicas de um elemento',
                    'Um comentário em CSS',
                    'Um seletor de classe',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 7,
                pergunta: 'Qual propriedade faz um elemento "flutuar"?',
                alternativas: ['position', 'float', 'align', 'display'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 8,
                pergunta: 'O que é "box-sizing: border-box"?',
                alternativas: [
                    'Inclui padding e border no tamanho total',
                    'Cria uma borda ao redor',
                    'Define o box model padrão',
                    'Remove todas as bordas',
                ],
                respostaCorreta: 0,
                dificuldade: 'medio',
            },
            {
                id: 9,
                pergunta: 'Qual seletor CSS tem maior especificidade?',
                alternativas: ['Classe (.btn)', 'ID (#header)', 'Tag (div)', 'Universal (*)'],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 10,
                pergunta: 'O que a propriedade "position: sticky" faz?',
                alternativas: [
                    'Remove o elemento do fluxo',
                    'Fixa o elemento após rolar até um ponto',
                    'Centraliza o elemento',
                    'Esconde o elemento',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
        ],
    },
    {
        id: 'logica',
        nome: 'Lógica',
        descricao: 'Pensamento computacional e algoritmos',
        icone: 'logic',
        cor: '#8B5CF6',
        perguntas: [
            {
                id: 1,
                pergunta: 'O que é um algoritmo?',
                alternativas: [
                    'Um tipo de computador',
                    'Uma sequência finita de passos para resolver um problema',
                    'Uma linguagem de programação',
                    'Um hardware especial',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'Qual é a complexidade do algoritmo de busca binária?',
                alternativas: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 3,
                pergunta: 'O que é recursão?',
                alternativas: [
                    'Um loop infinito',
                    'Uma função que chama a si mesma',
                    'Um tipo de variável',
                    'Um erro de programação',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 4,
                pergunta: 'O que é Big O notation?',
                alternativas: [
                    'Um tipo de dado',
                    'Descreve a eficiência/complexidade de um algoritmo',
                    'Uma linguagem de programação',
                    'Um framework',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 5,
                pergunta: 'Qual estrutura de dados segue FIFO (First In, First Out)?',
                alternativas: ['Stack (Pilha)', 'Queue (Fila)', 'Array', 'Tree (Árvore)'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 6,
                pergunta: 'Qual é a complexidade de um bubble sort no pior caso?',
                alternativas: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'],
                respostaCorreta: 2,
                dificuldade: 'medio',
            },
            {
                id: 7,
                pergunta: 'O que é uma tabela hash?',
                alternativas: [
                    'Uma tabela HTML',
                    'Estrutura que mapeia chaves para valores usando hash',
                    'Um tipo de banco de dados',
                    'Um algoritmo de sort',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 8,
                pergunta: 'O que é um dead lock?',
                alternativas: [
                    'Um erro de sintaxe',
                    'Quando dois processos ficam esperando um pelo outro',
                    'Um tipo de loop',
                    'Uma função recursiva',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 9,
                pergunta: 'Qual estrutura de dados usa LIFO (Last In, First Out)?',
                alternativas: ['Fila', 'Pilha (Stack)', 'Lista Ligada', 'Grafo'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 10,
                pergunta: 'O que é um árvore binária de busca (BST)?',
                alternativas: [
                    'Árvore onde cada nó tem no máximo 2 filhos com valores ordenados',
                    'Uma lista ligada especial',
                    'Um array bidimensional',
                    'Um tipo de grafo',
                ],
                respostaCorreta: 0,
                dificuldade: 'dificil',
            },
        ],
    },
    {
        id: 'sql',
        nome: 'SQL',
        descricao: 'Bancos de dados relacionais e consultas',
        icone: 'database',
        cor: '#336791',
        perguntas: [
            {
                id: 1,
                pergunta: 'O que significa SQL?',
                alternativas: [
                    'Structured Query Language',
                    'Simple Question Language',
                    'Standard Query Logic',
                    'System Query Language',
                ],
                respostaCorreta: 0,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'Qual comando é usado para buscar dados?',
                alternativas: ['GET', 'FETCH', 'SELECT', 'FIND'],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
            {
                id: 3,
                pergunta: 'O que é uma PRIMARY KEY?',
                alternativas: [
                    'Qualquer coluna',
                    'Identificador único de cada registro',
                    'Uma senha do banco',
                    'O nome da tabela',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 4,
                pergunta: 'Qual o comando para inserir dados?',
                alternativas: ['ADD INTO', 'INSERT INTO', 'PUT INTO', 'CREATE INTO'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 5,
                pergunta: 'O que é um JOIN?',
                alternativas: [
                    'Deletar dados',
                    'Combinar dados de duas ou mais tabelas',
                    'Criar uma tabela',
                    'Atualizar registros',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 6,
                pergunta: 'Qual a diferença entre WHERE e HAVING?',
                alternativas: [
                    'São iguais',
                    'WHERE filtra antes do GROUP BY, HAVING filtra depois',
                    'HAVING é mais rápido',
                    'WHERE só funciona com números',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 7,
                pergunta: 'O que é normalização de banco de dados?',
                alternativas: [
                    'Formatar o nome das tabelas',
                    'Organizar dados para reduzir redundância',
                    'Deletar dados duplicados',
                    'Criar backups',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 8,
                pergunta: 'Qual é o resultado de SELECT COUNT(*) FROM tabela?',
                alternativas: [
                    'Soma de todos os valores',
                    'Número total de registros',
                    'Média dos valores',
                    'Valor máximo',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 9,
                pergunta: 'O que é uma FOREIGN KEY?',
                alternativas: [
                    'Uma chave de criptografia',
                    'Referência a uma PRIMARY KEY de outra tabela',
                    'Uma coluna obrigatória',
                    'O nome da tabela estrangeira',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 10,
                pergunta: 'Qual a diferença entre DELETE e TRUNCATE?',
                alternativas: [
                    'São iguais',
                    'DELETE pode ter WHERE, TRUNCATE remove tudo e é mais rápido',
                    'TRUNCATE é mais lento',
                    'DELETE não pode ser revertido',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
        ],
    },
    {
        id: 'react',
        nome: 'React',
        descricao: 'A biblioteca mais popular para UIs',
        icone: 'react',
        cor: '#61DAFB',
        perguntas: [
            {
                id: 1,
                pergunta: 'O que é JSX?',
                alternativas: [
                    'Uma linguagem de programação',
                    'Extensão de sintaxe que permite escrever HTML em JavaScript',
                    'Um framework CSS',
                    'Um banco de dados',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'Qual hook é usado para gerenciar estado?',
                alternativas: ['useEffect', 'useState', 'useContext', 'useRef'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 3,
                pergunta: 'O que é o Virtual DOM?',
                alternativas: [
                    'O DOM real do navegador',
                    'Representação em memória do DOM para otimizar atualizações',
                    'Uma extensão do Chrome',
                    'Um servidor virtual',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 4,
                pergunta: 'Para que serve o useEffect?',
                alternativas: [
                    'Criar variáveis',
                    'Gerenciar efeitos colaterais (API calls, subscriptions)',
                    'Estilizar componentes',
                    'Criar rotas',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 5,
                pergunta: 'O que são Props em React?',
                alternativas: [
                    'Variáveis globais',
                    'Dados passados de pai para filho',
                    'Métodos do DOM',
                    'Estilos CSS',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 6,
                pergunta: 'O que é Context API?',
                alternativas: [
                    'Uma API REST',
                    'Forma de compartilhar dados sem prop drilling',
                    'Um banco de dados',
                    'Um gerenciador de rotas',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 7,
                pergunta: 'Qual é a finalidade do useCallback?',
                alternativas: [
                    'Criar callbacks assíncronos',
                    'Memorizar funções para evitar re-criações desnecessárias',
                    'Chamar APIs',
                    'Gerenciar formulários',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 8,
                pergunta: 'O que é "lifting state up"?',
                alternativas: [
                    'Mover estado para um componente filho',
                    'Mover estado para o componente pai comum',
                    'Deletar estado',
                    'Criar estado global',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 9,
                pergunta: 'O que são componentes controlados?',
                alternativas: [
                    'Componentes sem estado',
                    'Componentes onde o form é controlado pelo React state',
                    'Componentes de classe',
                    'Componentes que usam Redux',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 10,
                pergunta: 'O que é React.memo()?',
                alternativas: [
                    'Uma função de log',
                    'HOC que pula re-renders se props não mudaram',
                    'Um hook para memória',
                    'Um gerenciador de cache',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
        ],
    },
    {
        id: 'typescript',
        nome: 'TypeScript',
        descricao: 'JavaScript com tipagem estática e segura',
        icone: 'typescript',
        cor: '#3178C6',
        perguntas: [
            {
                id: 1,
                pergunta: 'Qual palavra-chave é usada para definir um tipo em TypeScript?',
                alternativas: ['type', 'typedef', 'define', 'typeset'],
                respostaCorreta: 0,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'Qual é a diferença entre "interface" e "type" no TypeScript?',
                alternativas: [
                    'Não existe diferença',
                    'Interface pode ser estendida com extends, type usa interseção &',
                    'Type é mais rápido',
                    'Interface só funciona com classes',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 3,
                pergunta: 'O que significa o tipo "unknown" em TypeScript?',
                alternativas: [
                    'Igual ao any',
                    'Um tipo que não existe',
                    'Um tipo seguro que requer verificação antes do uso',
                    'Um tipo para variáveis não inicializadas',
                ],
                respostaCorreta: 2,
                dificuldade: 'medio',
            },
            {
                id: 4,
                pergunta: 'O que são Generics em TypeScript?',
                alternativas: [
                    'Tipos genéricos que permitem reusar lógica com diferentes tipos',
                    'Funções que aceitam qualquer argumento',
                    'Classes abstratas',
                    'Módulos importados',
                ],
                respostaCorreta: 0,
                dificuldade: 'medio',
            },
            {
                id: 5,
                pergunta: 'Qual utilitário de tipo torna todas as propriedades opcionais?',
                alternativas: ['Required<T>', 'Partial<T>', 'Readonly<T>', 'Pick<T, K>'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 6,
                pergunta: 'O que é um "enum" em TypeScript?',
                alternativas: [
                    'Um tipo de array',
                    'Uma forma de definir constantes nomeadas',
                    'Um tipo de função',
                    'Uma classe especial',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 7,
                pergunta: 'O que é "type narrowing" em TypeScript?',
                alternativas: [
                    'Reduzir o tamanho do código',
                    'Refinar um tipo mais amplo para um mais específico',
                    'Remover propriedades de um tipo',
                    'Converter tipos automaticamente',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 8,
                pergunta: 'Qual é o resultado de "keyof" aplicado a uma interface?',
                alternativas: [
                    'Retorna os valores da interface',
                    'Retorna uma union das chaves da interface',
                    'Retorna o número de propriedades',
                    'Retorna um array',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 9,
                pergunta: 'O que o operador "as" faz em TypeScript?',
                alternativas: [
                    'Cria um alias',
                    'Faz uma asserção de tipo (type assertion)',
                    'Define uma variável',
                    'Importa um módulo',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 10,
                pergunta: 'O que são "mapped types" em TypeScript?',
                alternativas: [
                    'Tipos usados com Map()',
                    'Tipos que transformam propriedades de outro tipo',
                    'Tipos para arrays',
                    'Tipos numéricos',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
        ],
    },
    {
        id: 'java',
        nome: 'Java',
        descricao: 'Linguagem robusta para aplicações enterprise',
        icone: 'java',
        cor: '#E76F00',
        perguntas: [
            {
                id: 1,
                pergunta: 'Qual é o método principal de entrada em um programa Java?',
                alternativas: ['start()', 'main()', 'run()', 'init()'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'Qual palavra-chave é usada para herança em Java?',
                alternativas: ['inherits', 'implements', 'extends', 'super'],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
            {
                id: 3,
                pergunta: 'O que é um "ArrayList" em Java?',
                alternativas: [
                    'Um array fixo',
                    'Uma lista dinâmica baseada em array',
                    'Um tipo primitivo',
                    'Uma interface',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 4,
                pergunta: 'O que significa a palavra-chave "static" em Java?',
                alternativas: [
                    'A variável não pode ser alterada',
                    'O membro pertence à classe, não à instância',
                    'O método é privado',
                    'A classe é abstrata',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 5,
                pergunta: 'Qual é a diferença entre "==" e ".equals()" em Java?',
                alternativas: [
                    'Não há diferença',
                    '"==" compara referências, ".equals()" compara conteúdo',
                    '"==" é mais rápido',
                    '".equals()" só funciona com números',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 6,
                pergunta: 'O que é polimorfismo em Java?',
                alternativas: [
                    'Criar múltiplas classes',
                    'Um objeto assumir diferentes formas',
                    'Usar múltiplas interfaces',
                    'Herança múltipla',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 7,
                pergunta: 'O que é uma "interface" em Java?',
                alternativas: [
                    'Uma classe com métodos implementados',
                    'Um contrato que define métodos que a classe deve implementar',
                    'Um tipo de variável',
                    'Um pacote de importação',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 8,
                pergunta: 'O que é o Garbage Collector em Java?',
                alternativas: [
                    'Um debugger',
                    'Um gerenciador automático de memória que remove objetos sem referência',
                    'Um compilador',
                    'Um tipo de exceção',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 9,
                pergunta: 'O que são "Streams" em Java 8+?',
                alternativas: [
                    'Fluxos de entrada/saída de arquivos',
                    'API para processamento funcional de coleções',
                    'Threads paralelas',
                    'Conexões de rede',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 10,
                pergunta: 'O que é encapsulamento em Java?',
                alternativas: [
                    'Usar muitas classes',
                    'Esconder dados internos e expor apenas métodos públicos',
                    'Compilar o código',
                    'Criar pacotes',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
        ],
    },
    {
        id: 'csharp',
        nome: 'C#',
        descricao: 'Linguagem versátil da Microsoft para .NET',
        icone: 'csharp',
        cor: '#68217A',
        perguntas: [
            {
                id: 1,
                pergunta: 'Qual framework é mais usado com C#?',
                alternativas: ['Django', 'Spring', '.NET', 'Laravel'],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'O que é um "namespace" em C#?',
                alternativas: [
                    'Um tipo de variável',
                    'Um organizador lógico de classes e tipos',
                    'Um método especial',
                    'Um tipo de loop',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 3,
                pergunta: 'O que são "properties" em C#?',
                alternativas: [
                    'Variáveis globais',
                    'Membros que usam get/set para acessar campos privados',
                    'Métodos estáticos',
                    'Constantes',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 4,
                pergunta: 'O que é LINQ em C#?',
                alternativas: [
                    'Uma biblioteca de interface gráfica',
                    'Language Integrated Query para consultar coleções de dados',
                    'Um framework web',
                    'Um tipo de banco de dados',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 5,
                pergunta: 'O que é async/await em C#?',
                alternativas: [
                    'Um padrão de design',
                    'Palavras-chave para programação assíncrona',
                    'Um tipo de loop',
                    'Operadores matemáticos',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 6,
                pergunta: 'Qual é a diferença entre "struct" e "class" em C#?',
                alternativas: [
                    'Não há diferença',
                    'Struct é tipo valor (stack), class é tipo referência (heap)',
                    'Struct é mais lento',
                    'Class não suporta herança',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 7,
                pergunta: 'O que é um "delegate" em C#?',
                alternativas: [
                    'Um tipo de classe',
                    'Um tipo que referencia métodos com assinatura específica',
                    'Um operador',
                    'Um modificador de acesso',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 8,
                pergunta: 'O que significa a palavra-chave "sealed" em C#?',
                alternativas: [
                    'A classe é abstrata',
                    'A classe não pode ser herdada',
                    'A classe é estática',
                    'A classe é pública',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 9,
                pergunta: 'O que são "generics" em C#?',
                alternativas: [
                    'Classes sem métodos',
                    'Tipos parametrizados que aumentam a reutilização de código',
                    'Variáveis sem tipo',
                    'Funções anônimas',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 10,
                pergunta: 'O que é o padrão "using" em C#?',
                alternativas: [
                    'Importar namespaces apenas',
                    'Gerenciar automaticamente o descarte de recursos (IDisposable)',
                    'Declarar variáveis',
                    'Criar loops',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
        ],
    },
    {
        id: 'php',
        nome: 'PHP',
        descricao: 'Linguagem popular para desenvolvimento web server-side',
        icone: 'php',
        cor: '#777BB4',
        perguntas: [
            {
                id: 1,
                pergunta: 'Qual símbolo é usado para declarar variáveis em PHP?',
                alternativas: ['#', '@', '$', '&'],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'Qual função imprime texto na tela em PHP?',
                alternativas: ['print()', 'echo', 'write()', 'Todas as anteriores exceto write()'],
                respostaCorreta: 3,
                dificuldade: 'facil',
            },
            {
                id: 3,
                pergunta: 'Como se conecta a um banco MySQL com PDO em PHP?',
                alternativas: [
                    'mysql_connect()',
                    'new PDO("mysql:host=...;dbname=...", user, pass)',
                    'Database.connect()',
                    'mysqli_open()',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 4,
                pergunta: 'O que é Composer no ecossistema PHP?',
                alternativas: [
                    'Um editor de código',
                    'Um gerenciador de dependências',
                    'Um framework',
                    'Um servidor web',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 5,
                pergunta: 'O que é o Laravel?',
                alternativas: [
                    'Uma biblioteca JavaScript',
                    'O framework PHP mais popular para desenvolvimento web',
                    'Um banco de dados',
                    'Um servidor',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 6,
                pergunta: 'O que são "traits" em PHP?',
                alternativas: [
                    'Tipos de variáveis',
                    'Mecanismo para reutilizar código em classes sem herança múltipla',
                    'Funções anônimas',
                    'Interfaces especiais',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 7,
                pergunta: 'Qual é a diferença entre require e include em PHP?',
                alternativas: [
                    'Não há diferença',
                    'require gera erro fatal se falhar, include gera warning',
                    'include é mais rápido',
                    'require só funciona com classes',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 8,
                pergunta: 'O que é uma sessão (session) em PHP?',
                alternativas: [
                    'Um tipo de banco de dados',
                    'Forma de armazenar dados do usuário entre requisições no servidor',
                    'Um cookie',
                    'Uma conexão WebSocket',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 9,
                pergunta: 'O que significa o operador "=>" em PHP?',
                alternativas: [
                    'Comparação',
                    'Associa uma chave a um valor em arrays associativos',
                    'Arrow function',
                    'Herança',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 10,
                pergunta: 'O que são "namespaces" em PHP?',
                alternativas: [
                    'Variáveis globais',
                    'Forma de organizar código e evitar conflitos de nomes',
                    'Tipos de funções',
                    'Configurações do servidor',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
        ],
    },
    {
        id: 'go',
        nome: 'Go',
        descricao: 'Linguagem rápida e eficiente do Google',
        icone: 'go',
        cor: '#00ADD8',
        perguntas: [
            {
                id: 1,
                pergunta: 'Qual é o comando para compilar e executar um programa Go?',
                alternativas: ['go build', 'go run', 'go exec', 'go start'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'O que é uma "goroutine" em Go?',
                alternativas: [
                    'Um tipo de loop',
                    'Uma thread leve gerenciada pelo runtime do Go',
                    'Uma função recursiva',
                    'Um tipo de variável',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 3,
                pergunta: 'Qual keyword é usada para declarar variáveis curtas em Go?',
                alternativas: ['var', 'let', ':=', 'const'],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
            {
                id: 4,
                pergunta: 'O que são "channels" em Go?',
                alternativas: [
                    'Conexões de rede',
                    'Mecanismo para comunicação entre goroutines',
                    'Tipos de arrays',
                    'Módulos de importação',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 5,
                pergunta: 'Go possui classes e herança como Java?',
                alternativas: [
                    'Sim, são idênticas',
                    'Não, Go usa structs e composição ao invés de classes e herança',
                    'Sim, mas com sintaxe diferente',
                    'Apenas herança, sem classes',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 6,
                pergunta: 'Como o Go lida com erros?',
                alternativas: [
                    'Usando try/catch',
                    'Retornando erros como valores (múltiplos retornos)',
                    'Usando exceções',
                    'Ignorando erros automaticamente',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 7,
                pergunta: 'O que é o "defer" em Go?',
                alternativas: [
                    'Cancela a execução',
                    'Adia a execução de uma função para quando a função atual retornar',
                    'Define uma constante',
                    'Importa um pacote',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 8,
                pergunta: 'O que são interfaces em Go?',
                alternativas: [
                    'Classes abstratas',
                    'Conjuntos de assinaturas de métodos satisfeitos implicitamente',
                    'Tipos genéricos',
                    'Módulos externos',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 9,
                pergunta: 'Qual é o tipo zero-value de um ponteiro em Go?',
                alternativas: ['0', 'undefined', 'nil', 'null'],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
            {
                id: 10,
                pergunta: 'O que é "go mod" em Go?',
                alternativas: [
                    'Um comando para rodar testes',
                    'O sistema de gerenciamento de módulos e dependências',
                    'Um editor de código',
                    'Uma ferramenta de debug',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
        ],
    },
    {
        id: 'ruby',
        nome: 'Ruby',
        descricao: 'Linguagem elegante focada em produtividade',
        icone: 'ruby',
        cor: '#CC342D',
        perguntas: [
            {
                id: 1,
                pergunta: 'Qual framework web é mais famoso em Ruby?',
                alternativas: ['Django', 'Rails', 'Express', 'Laravel'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'Como se define um método em Ruby?',
                alternativas: ['function nome', 'def nome', 'method nome', 'fn nome'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 3,
                pergunta: 'O que são "blocks" em Ruby?',
                alternativas: [
                    'Tipos de variáveis',
                    'Trechos de código passados a métodos entre do/end ou {}',
                    'Classes especiais',
                    'Módulos de importação',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 4,
                pergunta: 'O que é um "symbol" em Ruby?',
                alternativas: [
                    'Uma string mutável',
                    'Um identificador imutável e leve, prefixado com ":"',
                    'Um número especial',
                    'Uma variável global',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 5,
                pergunta: 'Tudo em Ruby é um objeto?',
                alternativas: [
                    'Não, números não são objetos',
                    'Sim, incluindo números e booleanos',
                    'Apenas strings são objetos',
                    'Depende da versão',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 6,
                pergunta: 'O que são "gems" em Ruby?',
                alternativas: [
                    'Tipos de dados',
                    'Pacotes/bibliotecas distribuídas pelo RubyGems',
                    'Funções internas',
                    'Variáveis de ambiente',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 7,
                pergunta: 'O que é "duck typing" em Ruby?',
                alternativas: [
                    'Um tipo de dado',
                    'Se um objeto responde a um método, pode ser usado independente da classe',
                    'Tipagem estática',
                    'Um padrão de design',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 8,
                pergunta: 'O que é um "module" em Ruby?',
                alternativas: [
                    'O mesmo que uma classe',
                    'Uma coleção de métodos e constantes que pode ser incluída em classes (mixin)',
                    'Um arquivo de configuração',
                    'Uma variável global',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 9,
                pergunta: 'O que faz o método "each" em Ruby?',
                alternativas: [
                    'Cria um array',
                    'Itera sobre cada elemento de uma coleção',
                    'Ordena um array',
                    'Filtra elementos',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 10,
                pergunta: 'O que é "metaprogramming" em Ruby?',
                alternativas: [
                    'Programar em assembly',
                    'Código que escreve ou modifica código em tempo de execução',
                    'Usar múltiplos frameworks',
                    'Compilar Ruby para C',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
        ],
    },
    {
        id: 'kotlin',
        nome: 'Kotlin',
        descricao: 'Linguagem moderna para Android e JVM',
        icone: 'kotlin',
        cor: '#7F52FF',
        perguntas: [
            {
                id: 1,
                pergunta: 'Kotlin é interoperável com qual linguagem?',
                alternativas: ['Python', 'Java', 'C++', 'Ruby'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'Qual keyword declara uma variável imutável em Kotlin?',
                alternativas: ['var', 'val', 'const', 'let'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 3,
                pergunta: 'O que é "null safety" em Kotlin?',
                alternativas: [
                    'Variáveis nunca podem ser null',
                    'O sistema de tipos distingue entre referências nullable (?) e non-null',
                    'Null não existe em Kotlin',
                    'É o mesmo que Java',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 4,
                pergunta: 'O que é uma "data class" em Kotlin?',
                alternativas: [
                    'Uma classe para banco de dados',
                    'Classe que gera automaticamente equals, hashCode, toString e copy',
                    'Uma classe abstrata',
                    'Uma classe estática',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 5,
                pergunta: 'O que faz o operador "?." (safe call) em Kotlin?',
                alternativas: [
                    'Compara dois valores',
                    'Chama o método apenas se o objeto não for null',
                    'Cria uma nova instância',
                    'Converte tipos',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 6,
                pergunta: 'O que são "coroutines" em Kotlin?',
                alternativas: [
                    'Loops especiais',
                    'Forma leve de programação assíncrona/concorrente',
                    'Tipos de classes',
                    'Funções de extensão',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 7,
                pergunta: 'O que é uma "extension function" em Kotlin?',
                alternativas: [
                    'Uma função longa',
                    'Função que adiciona funcionalidade a uma classe sem modificá-la',
                    'Uma sobrecarga de operador',
                    'Uma função interna',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 8,
                pergunta: 'Qual keyword é usada para expressões when em Kotlin?',
                alternativas: ['switch', 'match', 'when', 'case'],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
            {
                id: 9,
                pergunta: 'O que é um "sealed class" em Kotlin?',
                alternativas: [
                    'Uma classe que não pode ter métodos',
                    'Uma classe com subclasses restritas definidas no mesmo arquivo',
                    'Uma classe imutável',
                    'Uma interface',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 10,
                pergunta: 'O que é "smart cast" em Kotlin?',
                alternativas: [
                    'Converter tipos manualmente',
                    'O compilador faz cast automático após verificação de tipo com "is"',
                    'Cast que nunca falha',
                    'Uma função de conversão',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
        ],
    },
    {
        id: 'swift',
        nome: 'Swift',
        descricao: 'Linguagem da Apple para iOS e macOS',
        icone: 'swift',
        cor: '#F05138',
        perguntas: [
            {
                id: 1,
                pergunta: 'Swift é usada principalmente para desenvolver apps de qual plataforma?',
                alternativas: ['Android', 'Windows', 'iOS/macOS', 'Linux'],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'O que são "optionals" em Swift?',
                alternativas: [
                    'Parâmetros opcionais',
                    'Tipos que podem conter um valor ou nil',
                    'Variáveis não tipadas',
                    'Constantes',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 3,
                pergunta: 'Qual keyword declara uma constante em Swift?',
                alternativas: ['var', 'let', 'const', 'val'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 4,
                pergunta: 'O que é "guard" em Swift?',
                alternativas: [
                    'Um loop especial',
                    'Instrução para saída antecipada quando condição não é atendida',
                    'Um tipo de classe',
                    'Um modificador de acesso',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 5,
                pergunta: 'O que são "closures" em Swift?',
                alternativas: [
                    'Classes sem nome',
                    'Blocos de código autocontidos que capturam valores do contexto',
                    'Loops fechados',
                    'Métodos estáticos',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 6,
                pergunta: 'O que é um "protocol" em Swift?',
                alternativas: [
                    'Um framework de rede',
                    'Similar a uma interface: define métodos e propriedades requeridos',
                    'Um tipo de variável',
                    'Um gerenciador de memória',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 7,
                pergunta: 'O que é ARC em Swift?',
                alternativas: [
                    'Um framework',
                    'Automatic Reference Counting para gerenciamento de memória',
                    'Um compilador',
                    'Uma IDE',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 8,
                pergunta: 'Qual é a diferença entre "struct" e "class" em Swift?',
                alternativas: [
                    'Não há diferença',
                    'Struct é tipo valor (copiado), class é tipo referência (compartilhado)',
                    'Struct é mais lento',
                    'Class não suporta métodos',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 9,
                pergunta: 'O que são "enums with associated values" em Swift?',
                alternativas: [
                    'Arrays de constantes',
                    'Enumerações onde cada caso pode carregar dados associados',
                    'Variáveis globais',
                    'Tipos genéricos',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 10,
                pergunta: 'O que é SwiftUI?',
                alternativas: [
                    'Uma linguagem de programação',
                    'Framework declarativo da Apple para construir interfaces',
                    'Um banco de dados',
                    'Uma biblioteca de testes',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
        ],
    },
    {
        id: 'cpp',
        nome: 'C++',
        descricao: 'Linguagem de alto desempenho para sistemas e games',
        icone: 'cpp',
        cor: '#00599C',
        perguntas: [
            {
                id: 1,
                pergunta: 'O que é um ponteiro em C++?',
                alternativas: [
                    'Um tipo de array',
                    'Uma variável que armazena o endereço de memória de outra variável',
                    'Uma função especial',
                    'Um operador',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'O que é RAII em C++?',
                alternativas: [
                    'Um compilador',
                    'Resource Acquisition Is Initialization: recursos atrelados ao tempo de vida do objeto',
                    'Um framework',
                    'Um tipo de dado',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 3,
                pergunta: 'O que faz o operador "::" em C++?',
                alternativas: [
                    'Compara valores',
                    'Acessa membros de um namespace ou classe (scope resolution)',
                    'Faz casting',
                    'Define constantes',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 4,
                pergunta: 'O que é um "smart pointer" em C++?',
                alternativas: [
                    'Um ponteiro mais rápido',
                    'Um wrapper que gerencia automaticamente a memória (unique_ptr, shared_ptr)',
                    'Um ponteiro para funções',
                    'Um alias para void*',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 5,
                pergunta: 'O que é STL em C++?',
                alternativas: [
                    'Um compilador',
                    'Standard Template Library: coleção de containers, algoritmos e iteradores',
                    'Uma IDE',
                    'Um framework web',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 6,
                pergunta: 'Qual é a diferença entre "new" e "malloc" em C++?',
                alternativas: [
                    'Não há diferença',
                    'new chama o construtor e retorna tipo correto, malloc apenas aloca memória',
                    'malloc é mais rápido',
                    'new não funciona com classes',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 7,
                pergunta: 'O que é polimorfismo em C++?',
                alternativas: [
                    'Criar muitas variáveis',
                    'Capacidade de chamar métodos derivados através de ponteiros/referências base (virtual)',
                    'Usar templates',
                    'Herança múltipla apenas',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 8,
                pergunta: 'O que são "templates" em C++?',
                alternativas: [
                    'Modelos de projeto',
                    'Mecanismo para escrever código genérico que funciona com diferentes tipos',
                    'Arquivos HTML',
                    'Macros do pré-processador',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 9,
                pergunta: 'O que faz "virtual" em um método de classe C++?',
                alternativas: [
                    'Torna o método privado',
                    'Permite que o método seja sobrescrito em classes derivadas (late binding)',
                    'Torna o método estático',
                    'Remove o método',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 10,
                pergunta: 'O que é um "destructor" em C++?',
                alternativas: [
                    'Uma função para deletar arquivos',
                    'Método especial (~Classe) chamado quando o objeto é destruído para liberar recursos',
                    'Um operador delete',
                    'Uma exceção',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
        ],
    },
];
