export interface Pergunta {
    id: number;
    pergunta: string;
    alternativas: string[];
    respostaCorreta: number;
    dificuldade: 'facil' | 'medio' | 'dificil';
}

export interface CategoriaQuiz {
    id: string;
    nome: string;
    descricao: string;
    icone: string;
    cor: string;
    perguntas: Pergunta[];
}

export const categorias: CategoriaQuiz[] = [
    {
        id: 'javascript',
        nome: 'JavaScript',
        descricao: 'Domine a linguagem da web moderna',
        icone: '⚡',
        cor: '#F7DF1E',
        perguntas: [
            {
                id: 1,
                pergunta: 'Qual método é usado para adicionar um elemento ao final de um array?',
                alternativas: ['push()', 'pop()', 'shift()', 'unshift()'],
                respostaCorreta: 0,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'O que o operador "===" faz em JavaScript?',
                alternativas: [
                    'Compara apenas valores',
                    'Compara valor e tipo',
                    'Atribui um valor',
                    'Compara referências',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 3,
                pergunta: 'Qual é o resultado de typeof null?',
                alternativas: ['"null"', '"undefined"', '"object"', '"boolean"'],
                respostaCorreta: 2,
                dificuldade: 'medio',
            },
            {
                id: 4,
                pergunta: 'O que é uma closure em JavaScript?',
                alternativas: [
                    'Uma função que fecha o navegador',
                    'Uma função que tem acesso ao escopo externo',
                    'Um método para fechar conexões',
                    'Um tipo de loop',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 5,
                pergunta: 'Qual método converte um JSON em objeto JavaScript?',
                alternativas: ['JSON.parse()', 'JSON.stringify()', 'JSON.convert()', 'JSON.toObject()'],
                respostaCorreta: 0,
                dificuldade: 'facil',
            },
            {
                id: 6,
                pergunta: 'O que a keyword "let" faz diferente de "var"?',
                alternativas: [
                    'Nada, são iguais',
                    'let tem escopo de bloco',
                    'let é mais rápido',
                    'let só funciona em funções',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 7,
                pergunta: 'Qual é o output de: console.log(0.1 + 0.2 === 0.3)?',
                alternativas: ['true', 'false', 'undefined', 'NaN'],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 8,
                pergunta: 'O que é o Event Loop no JavaScript?',
                alternativas: [
                    'Um loop for especial',
                    'Gerencia a execução assíncrona de callbacks',
                    'Um evento de mouse',
                    'Um tipo de array',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 9,
                pergunta: 'Qual método retorna um novo array com elementos filtrados?',
                alternativas: ['map()', 'filter()', 'reduce()', 'find()'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 10,
                pergunta: 'O que são Promises em JavaScript?',
                alternativas: [
                    'Variáveis globais',
                    'Representam o resultado futuro de uma operação assíncrona',
                    'Funções síncronas',
                    'Tipos de dados primitivos',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
        ],
    },
    {
        id: 'python',
        nome: 'Python',
        descricao: 'A linguagem mais versátil do mundo',
        icone: '🐍',
        cor: '#3776AB',
        perguntas: [
            {
                id: 1,
                pergunta: 'Qual é a forma correta de criar uma lista em Python?',
                alternativas: ['list = (1, 2, 3)', 'list = [1, 2, 3]', 'list = {1, 2, 3}', 'list = <1, 2, 3>'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'O que faz o método strip() em uma string?',
                alternativas: [
                    'Remove todos os espaços',
                    'Remove espaços do início e fim',
                    'Remove caracteres especiais',
                    'Inverte a string',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 3,
                pergunta: 'Qual é a diferença entre uma lista e uma tupla?',
                alternativas: [
                    'Nenhuma diferença',
                    'Tuplas são imutáveis',
                    'Listas são mais rápidas',
                    'Tuplas só aceitam números',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 4,
                pergunta: 'O que é um decorator em Python?',
                alternativas: [
                    'Um tipo de variável',
                    'Uma função que modifica outra função',
                    'Um comentário especial',
                    'Um tipo de classe',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 5,
                pergunta: 'Como se cria um dicionário vazio em Python?',
                alternativas: ['dict = []', 'dict = ()', 'dict = {}', 'dict = set()'],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
            {
                id: 6,
                pergunta: 'Qual keyword é usada para herança de classes?',
                alternativas: ['extends', 'inherits', 'class Filho(Pai)', 'class Filho extends Pai'],
                respostaCorreta: 2,
                dificuldade: 'medio',
            },
            {
                id: 7,
                pergunta: 'O que é list comprehension?',
                alternativas: [
                    'Uma forma de ler listas',
                    'Sintaxe concisa para criar listas',
                    'Um tipo de sort',
                    'Um método de lista',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 8,
                pergunta: 'Qual é o resultado de: len("Python")?',
                alternativas: ['5', '6', '7', 'Error'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 9,
                pergunta: 'O que é o GIL (Global Interpreter Lock)?',
                alternativas: [
                    'Um framework',
                    'Mecanismo que impede execução paralela real de threads',
                    'Um gerenciador de pacotes',
                    'Um tipo de variável global',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 10,
                pergunta: 'Qual é a forma correta de importar um módulo?',
                alternativas: ['#include math', 'using math', 'import math', 'require("math")'],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
        ],
    },
    {
        id: 'htmlcss',
        nome: 'HTML & CSS',
        descricao: 'Os fundamentos de toda página web',
        icone: '🎨',
        cor: '#E44D26',
        perguntas: [
            {
                id: 1,
                pergunta: 'O que significa HTML?',
                alternativas: [
                    'Hyper Text Markup Language',
                    'High Tech Modern Language',
                    'Home Tool Markup Language',
                    'Hyper Transfer Markup Language',
                ],
                respostaCorreta: 0,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'Qual tag é usada para o maior título?',
                alternativas: ['<heading>', '<h6>', '<h1>', '<title>'],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
            {
                id: 3,
                pergunta: 'O que é Flexbox?',
                alternativas: [
                    'Um framework CSS',
                    'Um modelo de layout unidimensional',
                    'Um tipo de animação',
                    'Uma propriedade de cor',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 4,
                pergunta: 'Qual propriedade CSS controla a transparência?',
                alternativas: ['visibility', 'transparency', 'opacity', 'display'],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
            {
                id: 5,
                pergunta: 'O que é CSS Grid?',
                alternativas: [
                    'Um modelo de layout bidimensional',
                    'Uma tabela HTML',
                    'Um framework JavaScript',
                    'Um tipo de fonte',
                ],
                respostaCorreta: 0,
                dificuldade: 'medio',
            },
            {
                id: 6,
                pergunta: 'Qual a diferença entre margin e padding?',
                alternativas: [
                    'São iguais',
                    'Margin é espaço externo, padding é interno',
                    'Padding é espaço externo, margin é interno',
                    'Ambos controlam a cor',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 7,
                pergunta: 'O que é um pseudo-elemento CSS?',
                alternativas: [
                    'Um elemento HTML falso',
                    'Permite estilizar partes específicas de um elemento',
                    'Um comentário em CSS',
                    'Um seletor de classe',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 8,
                pergunta: 'Qual propriedade faz um elemento "flutuar"?',
                alternativas: ['position', 'float', 'align', 'display'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 9,
                pergunta: 'O que significa a sigla CSS?',
                alternativas: [
                    'Computer Style Sheets',
                    'Creative Style System',
                    'Cascading Style Sheets',
                    'Colorful Style Sheets',
                ],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
            {
                id: 10,
                pergunta: 'O que é "box-sizing: border-box"?',
                alternativas: [
                    'Inclui padding e border no tamanho total',
                    'Cria uma borda ao redor',
                    'Define o box model padrão',
                    'Remove todas as bordas',
                ],
                respostaCorreta: 0,
                dificuldade: 'medio',
            },
        ],
    },
    {
        id: 'logica',
        nome: 'Lógica',
        descricao: 'Pensamento computacional e algoritmos',
        icone: '🧠',
        cor: '#8B5CF6',
        perguntas: [
            {
                id: 1,
                pergunta: 'O que é um algoritmo?',
                alternativas: [
                    'Um tipo de computador',
                    'Uma sequência finita de passos para resolver um problema',
                    'Uma linguagem de programação',
                    'Um hardware especial',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'Qual é a complexidade do algoritmo de busca binária?',
                alternativas: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 3,
                pergunta: 'O que é recursão?',
                alternativas: [
                    'Um loop infinito',
                    'Uma função que chama a si mesma',
                    'Um tipo de variável',
                    'Um erro de programação',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 4,
                pergunta: 'O que é Big O notation?',
                alternativas: [
                    'Um tipo de dado',
                    'Descreve a eficiência/complexidade de um algoritmo',
                    'Uma linguagem de programação',
                    'Um framework',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 5,
                pergunta: 'Qual estrutura de dados segue FIFO (First In, First Out)?',
                alternativas: ['Stack (Pilha)', 'Queue (Fila)', 'Array', 'Tree (Árvore)'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 6,
                pergunta: 'Qual é a complexidade de um bubble sort no pior caso?',
                alternativas: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'],
                respostaCorreta: 2,
                dificuldade: 'medio',
            },
            {
                id: 7,
                pergunta: 'O que é uma tabela hash?',
                alternativas: [
                    'Uma tabela HTML',
                    'Estrutura que mapeia chaves para valores usando hash',
                    'Um tipo de banco de dados',
                    'Um algoritmo de sort',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 8,
                pergunta: 'O que é um dead lock?',
                alternativas: [
                    'Um erro de sintaxe',
                    'Quando dois processos ficam esperando um pelo outro',
                    'Um tipo de loop',
                    'Uma função recursiva',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 9,
                pergunta: 'Qual estrutura de dados usa LIFO (Last In, First Out)?',
                alternativas: ['Fila', 'Pilha (Stack)', 'Lista Ligada', 'Grafo'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 10,
                pergunta: 'O que é um árvore binária de busca (BST)?',
                alternativas: [
                    'Árvore onde cada nó tem no máximo 2 filhos com valores ordenados',
                    'Uma lista ligada especial',
                    'Um array bidimensional',
                    'Um tipo de grafo',
                ],
                respostaCorreta: 0,
                dificuldade: 'dificil',
            },
        ],
    },
    {
        id: 'sql',
        nome: 'SQL',
        descricao: 'Bancos de dados relacionais e consultas',
        icone: '🗄️',
        cor: '#336791',
        perguntas: [
            {
                id: 1,
                pergunta: 'O que significa SQL?',
                alternativas: [
                    'Structured Query Language',
                    'Simple Question Language',
                    'Standard Query Logic',
                    'System Query Language',
                ],
                respostaCorreta: 0,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'Qual comando é usado para buscar dados?',
                alternativas: ['GET', 'FETCH', 'SELECT', 'FIND'],
                respostaCorreta: 2,
                dificuldade: 'facil',
            },
            {
                id: 3,
                pergunta: 'O que é uma PRIMARY KEY?',
                alternativas: [
                    'Qualquer coluna',
                    'Identificador único de cada registro',
                    'Uma senha do banco',
                    'O nome da tabela',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 4,
                pergunta: 'Qual o comando para inserir dados?',
                alternativas: ['ADD INTO', 'INSERT INTO', 'PUT INTO', 'CREATE INTO'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 5,
                pergunta: 'O que é um JOIN?',
                alternativas: [
                    'Deletar dados',
                    'Combinar dados de duas ou mais tabelas',
                    'Criar uma tabela',
                    'Atualizar registros',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 6,
                pergunta: 'Qual a diferença entre WHERE e HAVING?',
                alternativas: [
                    'São iguais',
                    'WHERE filtra antes do GROUP BY, HAVING filtra depois',
                    'HAVING é mais rápido',
                    'WHERE só funciona com números',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 7,
                pergunta: 'O que é normalização de banco de dados?',
                alternativas: [
                    'Formatar o nome das tabelas',
                    'Organizar dados para reduzir redundância',
                    'Deletar dados duplicados',
                    'Criar backups',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 8,
                pergunta: 'Qual é o resultado de SELECT COUNT(*) FROM tabela?',
                alternativas: [
                    'Soma de todos os valores',
                    'Número total de registros',
                    'Média dos valores',
                    'Valor máximo',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 9,
                pergunta: 'O que é uma FOREIGN KEY?',
                alternativas: [
                    'Uma chave de criptografia',
                    'Referência a uma PRIMARY KEY de outra tabela',
                    'Uma coluna obrigatória',
                    'O nome da tabela estrangeira',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 10,
                pergunta: 'Qual a diferença entre DELETE e TRUNCATE?',
                alternativas: [
                    'São iguais',
                    'DELETE pode ter WHERE, TRUNCATE remove tudo e é mais rápido',
                    'TRUNCATE é mais lento',
                    'DELETE não pode ser revertido',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
        ],
    },
    {
        id: 'react',
        nome: 'React',
        descricao: 'A biblioteca mais popular para UIs',
        icone: '⚛️',
        cor: '#61DAFB',
        perguntas: [
            {
                id: 1,
                pergunta: 'O que é JSX?',
                alternativas: [
                    'Uma linguagem de programação',
                    'Extensão de sintaxe que permite escrever HTML em JavaScript',
                    'Um framework CSS',
                    'Um banco de dados',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 2,
                pergunta: 'Qual hook é usado para gerenciar estado?',
                alternativas: ['useEffect', 'useState', 'useContext', 'useRef'],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 3,
                pergunta: 'O que é o Virtual DOM?',
                alternativas: [
                    'O DOM real do navegador',
                    'Representação em memória do DOM para otimizar atualizações',
                    'Uma extensão do Chrome',
                    'Um servidor virtual',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 4,
                pergunta: 'Para que serve o useEffect?',
                alternativas: [
                    'Criar variáveis',
                    'Gerenciar efeitos colaterais (API calls, subscriptions)',
                    'Estilizar componentes',
                    'Criar rotas',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 5,
                pergunta: 'O que são Props em React?',
                alternativas: [
                    'Variáveis globais',
                    'Dados passados de pai para filho',
                    'Métodos do DOM',
                    'Estilos CSS',
                ],
                respostaCorreta: 1,
                dificuldade: 'facil',
            },
            {
                id: 6,
                pergunta: 'O que é Context API?',
                alternativas: [
                    'Uma API REST',
                    'Forma de compartilhar dados sem prop drilling',
                    'Um banco de dados',
                    'Um gerenciador de rotas',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 7,
                pergunta: 'Qual é a finalidade do useCallback?',
                alternativas: [
                    'Criar callbacks assíncronos',
                    'Memorizar funções para evitar re-criações desnecessárias',
                    'Chamar APIs',
                    'Gerenciar formulários',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
            {
                id: 8,
                pergunta: 'O que é "lifting state up"?',
                alternativas: [
                    'Mover estado para um componente filho',
                    'Mover estado para o componente pai comum',
                    'Deletar estado',
                    'Criar estado global',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 9,
                pergunta: 'O que são componentes controlados?',
                alternativas: [
                    'Componentes sem estado',
                    'Componentes onde o form é controlado pelo React state',
                    'Componentes de classe',
                    'Componentes que usam Redux',
                ],
                respostaCorreta: 1,
                dificuldade: 'medio',
            },
            {
                id: 10,
                pergunta: 'O que é React.memo()?',
                alternativas: [
                    'Uma função de log',
                    'HOC que pula re-renders se props não mudaram',
                    'Um hook para memória',
                    'Um gerenciador de cache',
                ],
                respostaCorreta: 1,
                dificuldade: 'dificil',
            },
        ],
    },
];
